title: Las Crónicas
description: Juro dedicar mi vida a la lucha contra la piratería, la crueldad y la injusticia y pido que mis hijos y los hijos de mis hijos hagan lo mismo
theme: just-the-docs

url: https://kit-walker-1945.github.io/cronicas_he

aux_links:
  Template Repository: https://github.com/kit-walker-1945/cronicas_he

# Color scheme supports "light" (default) and "dark"
color_scheme: dark

