title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://kit-walker-1945.github.io/cronicas_he

aux_links:
  Template Repository: https://github.com/kit-walker-1945/cronicas_he
